# Generated by Django 5.2 on 2025-04-15 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_contratocliente'),
        ('ordens', '0006_produtoutilizado_ordemservico_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria de Equipamento',
                'verbose_name_plural': 'Categorias de Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Modelo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de Instalação')),
                ('data_garantia_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Garantia')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='ativo', max_length=15, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('local_instalacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Instalação')),
                ('especificacoes_tecnicas', models.TextField(blank=True, null=True, verbose_name='Especificações Técnicas')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipamentos', verbose_name='Foto')),
                ('manual', models.FileField(blank=True, null=True, upload_to='equipamentos/manuais', verbose_name='Manual')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='equipamentos.categoriaequipamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['cliente__nome', 'nome'],
                'unique_together': {('cliente', 'numero_serie')},
            },
        ),
        migrations.CreateModel(
            name='ManutencaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('instalacao', 'Instalação'), ('atualizacao', 'Atualização')], max_length=20, verbose_name='Tipo')),
                ('data', models.DateTimeField(verbose_name='Data da Manutenção')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('solucao', models.TextField(blank=True, null=True, verbose_name='Solução Aplicada')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='equipamentos.equipamento')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_equipamento', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Manutenção de Equipamento',
                'verbose_name_plural': 'Manutenções de Equipamentos',
                'ordering': ['-data'],
            },
        ),
    ]
