# Generated by Django 5.2 on 2025-04-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('solucao', models.TextField(blank=True, null=True, verbose_name='Solução Aplicada')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Agendamento')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('aguardando_peca', 'Aguardando Peça'), ('aguardando_cliente', 'Aguardando Cliente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('numero_endereco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('valor_servico', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Serviço')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor das Peças')),
                ('valor_deslocamento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Deslocamento')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Avaliação (1-5)')),
                ('feedback_cliente', models.TextField(blank=True, null=True, verbose_name='Feedback do Cliente')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('interno', models.BooleanField(default=False, verbose_name='Anotações Internas')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='ordens.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='clientes.cliente')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('interno', models.BooleanField(default=False, verbose_name='Interno')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to='anexos', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
