# Generated by Django 5.2 on 2025-04-09 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='feedback_cliente',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='interno',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='atualizado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='avaliacao_cliente',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação do Cliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='comentario_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário do Cliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='criado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='latitude_fim',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude fim'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='latitude_inicio',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude início'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='link_pagamento',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Pagamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='longitude_fim',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude fim'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='longitude_inicio',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude início'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacoes_internas',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Internas'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='precisao_fim',
            field=models.FloatField(blank=True, null=True, verbose_name='Precisão fim (metros)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='precisao_inicio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precisão início (metros)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='preferencia_contato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Preferência de Contato'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_deslocamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Deslocamento'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_pecas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Peças/Materiais'),
        ),
    ]
