# Generated by Django 5.2 on 2025-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_remove_ordemservico_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='id_tecnico',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID do Técnico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='nome_tecnico',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Técnico'),
        ),
    ]
