# Generated by Django 5.2 on 2025-04-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0004_ordemservico_id_tecnico_ordemservico_nome_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='reportando_problema',
            field=models.BooleanField(default=False, verbose_name='Reportando Problema'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='resolvido',
            field=models.BooleanField(default=False, verbose_name='Problema Resolvido'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tipo_autor',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('operador', 'Operador'), ('sistema', 'Sistema'), ('cliente', 'Cliente')], default='operador', max_length=20, verbose_name='Tipo de Autor'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tipo_problema',
            field=models.CharField(choices=[('sem_problema', 'Sem Problema'), ('acesso', 'Problema de Acesso'), ('material', 'Falta de Material'), ('cliente', 'Problema com Cliente'), ('equipamento', 'Problema com Equipamento'), ('tecnico', 'Problema com Técnico'), ('outro', 'Outro Problema')], default='sem_problema', max_length=20, verbose_name='Tipo de Problema'),
        ),
    ]
