# Generated by Django 5.2 on 2025-04-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0005_comentario_data_resolucao_and_more'),
        ('produtos', '0002_unidademedida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantidade Utilizada')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário (na OS)')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_utilizados', to='ordens.ordemservico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilizado_em_ordens', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Produto Utilizado na OS',
                'verbose_name_plural': 'Produtos Utilizados na OS',
                'unique_together': {('ordem_servico', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='ordens_servico', through='ordens.ProdutoUtilizado', to='produtos.produto'),
        ),
    ]
