# Generated by Django 5.2 on 2025-04-15 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('ordens', '0006_produtoutilizado_ordemservico_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='equipamentos.equipamento'),
        ),
    ]
