# Generated by Django 5.2 on 2025-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0007_ordemservico_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
