# Generated by Django 5.2 on 2025-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0008_categoria_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='assinatura_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura Digital do Cliente'),
        ),
    ]
