# Generated by Django 5.2 on 2025-04-07 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('total_ordens', models.IntegerField(default=0, verbose_name='Total de Ordens')),
                ('ordens_abertas', models.IntegerField(default=0, verbose_name='Ordens Abertas')),
                ('ordens_andamento', models.IntegerField(default=0, verbose_name='Ordens em Andamento')),
                ('ordens_aguardando', models.IntegerField(default=0, verbose_name='Ordens Aguardando')),
                ('ordens_concluidas', models.IntegerField(default=0, verbose_name='Ordens Concluídas')),
                ('ordens_canceladas', models.IntegerField(default=0, verbose_name='Ordens Canceladas')),
                ('satisfacao_media', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Satisfação Média')),
                ('tempo_medio_atendimento', models.DurationField(default=datetime.timedelta(0), verbose_name='Tempo Médio de Atendimento')),
                ('faturamento_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Faturamento do Dia')),
            ],
            options={
                'verbose_name': 'Métrica Diária',
                'verbose_name_plural': 'Métricas Diárias',
                'ordering': ['-data'],
            },
        ),
    ]
