# Generated by Django 5.2 on 2025-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='codigo',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ] 