# Generated by Django 4.2 on 2025-04-23 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_menu_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissao',
            unique_together={('menu', 'grupo')},
        ),
        migrations.AddField(
            model_name='permissao',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_diretas', to='usuarios.perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='permissoes_customizadas',
            field=models.ManyToManyField(blank=True, related_name='perfis_customizados', to='usuarios.permissao'),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='usuarios.grupopermissao'),
        ),
        migrations.AlterUniqueTogether(
            name='permissao',
            unique_together={('menu', 'grupo'), ('menu', 'perfil')},
        ),
        migrations.AddConstraint(
            model_name='permissao',
            constraint=models.CheckConstraint(check=models.Q(grupo__isnull=False) | models.Q(perfil__isnull=False), name='permissao_grupo_ou_perfil'),
        ),
    ]
