# Generated by Django 5.2 on 2025-04-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_remove_ordemservico_avaliacao_and_more'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizacaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('tipo', models.CharField(choices=[('inicio', 'Início do Atendimento'), ('fim', 'Fim do Atendimento'), ('atualizacao', 'Atualização Durante Atendimento')], max_length=20, verbose_name='Tipo')),
                ('precisao', models.FloatField(blank=True, null=True, verbose_name='Precisão (metros)')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='ordens.ordemservico')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes_atendimento', to='tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Localização de Atendimento',
                'verbose_name_plural': 'Localizações de Atendimento',
                'ordering': ['-data_hora'],
            },
        ),
    ]
