# Generated by Django 4.2 on 2023-04-24 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_registroponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnico',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ] 