# Generated by Django 5.2 on 2025-04-24 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0004_tecnico_data_campos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='ultima_atualizacao',
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='codigo',
            field=models.CharField(max_length=15, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tecnicos/'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='habilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nivel',
            field=models.CharField(choices=[('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('especialista', 'Especialista')], default='junior', max_length=20),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_atendimento', 'Em Atendimento'), ('ausente', 'Ausente'), ('ferias', 'Férias'), ('licenca', 'Licença')], default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='ultima_atualizacao_local',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to=settings.AUTH_USER_MODEL),
        ),
    ]
