# Generated by Django 5.2 on 2025-04-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos/clientes', verbose_name='Arquivo do Contrato')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contrato de Cliente',
                'verbose_name_plural': 'Contratos de Clientes',
                'ordering': ['-data_upload'],
            },
        ),
    ]
