# Generated by Django 5.2 on 2025-04-23 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('principal', models.BooleanField(default=False, help_text='Indica se este usuário é o contato principal da empresa', verbose_name='Contato Principal')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='clientes.cliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_vinculo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário do Cliente',
                'verbose_name_plural': 'Usuários dos Clientes',
                'unique_together': {('usuario', 'cliente')},
            },
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
