# Generated by Django 5.2 on 2025-04-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_empresa_alter_cliente_bairro_alter_cliente_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_clientes', to='clientes.empresa'),
        ),
    ]
