# Generated by Django 5.2 on 2025-04-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_clienteusuario_empresa'),
    ]

    operations = [
    ]
